[package]
name = "umya-spreadsheet"
version = "0.8.0"
authors = ["MathNya <umya.net.info@gmail.com>"]
repository = "https://github.com/MathNya/umya-spreadsheet"
keywords = ["excel", "spreadsheet", "xlsx", "reader", "writer"]
license = "MIT"
readme = "README.md"
description = "umya-spreadsheet is a library written in pure Rust and read and write xlsx file."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = { version = "0.23", features = [ "serialize" ] }
zip = {version = "0.6.2", default-features = false, features = ["deflate"]}
md-5 = "0.10.1"
lazy_static = "1.4.0"
thousands = "0.2.0"
chrono = "0.4.19"
encoding_rs = "0.8.30"
image = "0.24.1"
hashbrown = "0.12.0"
ahash = "0.8.0"
fancy-regex = "0.10.0"
base64 = "0.13.0"
getrandom = "0.2"
byteorder = "1.4.3"
cfb = "0.7.3"

[lib]
doctest = false
